
/* Original code[1] Copyright (c) 2022 Shane Celis[2]
   Licensed under the MIT License[3]

   This comment generated by code-cite[3].

   [1]: https://github.com/shanecelis/SeawispHunter.RolePlay.Attributes
   [2]: https://twitter.com/shanecelis
   [3]: https://opensource.org/licenses/MIT
   [4]: https://github.com/shanecelis/code-cite
*/

using System;
using System.Linq;
using System.Threading;
using Xunit;

using SeawispHunter.RolePlay.Attributes;
namespace SeawispHunter.RolePlay.Attributes.Test {
  public class A {
    public static int M<T>(T item) where T : struct => 0;
    // public static int M<T>(T item) where T : class => 1;
  }

public class GenericWhereTests {
  [Fact] public void TestWhereExclusions() {
    Assert.Equal(0, A.M<float>(1f));

  }

}
}
