/* Original code[1] Copyright (c) 2022 Shane Celis[2]
   Licensed under the MIT License[3]

   This comment generated by code-cite[3].

   [1]: https://github.com/shanecelis/SeawispHunter.RolePlay.Attributes
   [2]: https://twitter.com/shanecelis
   [3]: https://opensource.org/licenses/MIT
   [4]: https://github.com/shanecelis/code-cite
*/

#if NET6_0_OR_GREATER
using System.Numerics;
#endif
using System;

namespace SeawispHunter.RolePlay.Attributes {

/** This stat class represents the style of stat altering presented by Daniel
    Sidhion in this article[1].

    Currently this class only works with float and int but other numerical types
    can be easily added.

    [1]: https://gamedevelopment.tutsplus.com/tutorials/using-the-composite-design-pattern-for-an-rpg-attributes-system--gamedev-243
*/
public class SidhionStat<T> : ModifiableValue<T>
#if NET6_0_OR_GREATER
  where T : INumber<T>
#endif
{
  public IModifiableValue<T> rawBonusesPlus = new ModifiableValue<T>();
  public IModifiableValue<T> rawBonusesMultiply = new ModifiableValue<T>() {
#if NET6_0_OR_GREATER
    baseValue = T.One
#else
    baseValue = one
#endif
  };
  public IModifiableValue<T> finalBonusesPlus = new ModifiableValue<T>();
  public IModifiableValue<T> finalBonusesMultiply = new ModifiableValue<T>() {
#if NET6_0_OR_GREATER
    baseValue = T.One
#else
    baseValue = one
#endif
  };

  public SidhionStat() {
    modifiers.Add(Modifier.Plus<T,T>(rawBonusesPlus));
    modifiers.Add(Modifier.Multiply<T,T>(rawBonusesMultiply));
    modifiers.Add(Modifier.Plus<T,T>(finalBonusesPlus));
    modifiers.Add(Modifier.Multiply<T,T>(finalBonusesMultiply));
  }

#if ! NET6_0_OR_GREATER
  private static T one {
    get {
      switch (Type.GetTypeCode(typeof(T))) {
        case TypeCode.Single:
          return (T) (object) 1f;
        case TypeCode.Int32:
          return (T) (object) 1;
        default:
          throw new NotImplementedException($"No `one` case provided for type {typeof(T)}. Update `one` property.");
      }
    }
  }
#endif
}

}
